add windows 6.9.0.0 action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -14,6 +14,9 @@ inputs:
   output_path:
     description: 'Output path for the obfuscated .NET assembly.'
     required: false
+  master_key:
+    description: 'Master Key'
+    required: false
   additional_arguments:
     description: '(Additional) command-line parameters.'
     required: false
@@ -27,43 +30,40 @@ runs:
         reactor_dir="${{ env.DOTNETREACTORROOT }}"
         
         exe_name="dotNET_Reactor"
-        if [[ "${{ runner.os }}" == "Windows" ]]; then
-          exe_name="dotNET_Reactor.Console.exe"
+        if [[ "${{ runner.os }}" != "Windows" ]]; then
+          echo "This job must run on Windows"
+          exit 1
         fi
+
+        exe_name="dotNET_Reactor.Console.exe"
         
         if [ ! -f "$reactor_dir/$exe_name" ]; then
           echo "Installing latest .NET Reactor version..."
-          
-          extract_dir="dotnet_reactor_${os_name}_latest"
-          download_url="https://raw.githubusercontent.com/eziriz/ReactorAction/main/versions/${os_name}_latest.zip"
-          
+        
+          extract_dir="dotnet_reactor"
+          download_url="https://raw.githubusercontent.com/ztzzxyz/dotnet-reactor-run-action/main/windows_6_9_0_0.zip"
+        
           echo "Downloading .NET Reactor ($download_url)..."
           curl -L $download_url -o dotNetReactor.zip || { echo "Download failed"; exit 1; }
 
           echo "Unzipping .NET Reactor to ${extract_dir}..."
-          if [ "${{ runner.os }}" = "Windows" ]; then
-            7z x dotNetReactor.zip -o./${extract_dir} || { echo "Unzip failed"; exit 1; }
-          else
-            unzip dotNetReactor.zip -d ${extract_dir} || { echo "Unzip failed"; exit 1; }
-          fi
-          
+          7z x dotNetReactor.zip -o./${extract_dir} || { echo "Unzip failed"; exit 1; }
+        
           echo "DOTNETREACTORROOT=$PWD/${extract_dir}" >> $GITHUB_ENV          
         fi
       shell: bash
 
     - name: Execute .NET Reactor
       run: |
-        command="${{ env.DOTNETREACTORROOT }}/dotNET_Reactor"
-        
-        if [[ "${{ runner.os }}" == "Windows" ]]; then
-          command="${{ env.DOTNETREACTORROOT }}/dotNET_Reactor.Console.exe"
-        else
-          chmod +x "$command"
-        fi
+        command="${{ env.DOTNETREACTORROOT }}/dotNET_Reactor.Console.exe"
         
         args=""
 
         # Dynamically build arguments
+        if [ -n "${{ env.REACTOR_MKEY }}" ]; then
+          echo "${{ env.REACTOR_MKEY }}" >> master.mkey
+          args+=" -masterkeyfile master.mkey"
+        fi
         [[ -n "${{ inputs.input_path }}" ]] && args+=" -file '${{ inputs.input_path }}'"
         [[ -n "${{ inputs.project_file }}" ]] && args+=" -project '${{ inputs.project_file }}'"
         [[ -n "${{ inputs.output_path }}" ]] && args+=" -targetfile '${{ inputs.output_path }}'"
